from django.conf.urls.defaults import *

urlpatterns = patterns('djangogolf.web.views',
#    (r'web^$', 'showarticle'),
    (r'^$', 'index'),
    (r'^home/$', 'index'),
    (r'^sorry/$', 'sorry'),
    (r'^adduser/(?P<code>\d+)/$', 'adduser'),
    (r'^edituser/$', 'edituser'),
    (r'^register/$', 'register'),
    (r'^calculatehandicap/$', 'calculatehandicap'),
    (r'^displayhandicap/$', 'displayhandicap'),
    (r'^addcourse/((?P<id>\d+)/)?$', 'addcourse'),
    (r'^addmember/((?P<id>\d+)/)?$', 'addmember'),
    (r'^closetournament/((?P<trn>\d+)/)?$', 'closetournament'),
    (r'^tournamentfull/((?P<trn>\d+)/)?$', 'tournamentfull'),
    (r'^regthank/(?P<id>\d+)/$', 'regthank'),
    (r'^showdraw/(?P<drw>\d+)/$', 'showdraw'),
    (r'^adjustdraw/(?P<drw>\d+)/$', 'adjustdraw'),
    (r'^calculatehandicap/(?P<mem>\d+)/$', 'calculatehandicap'),
    (r'^finaldraw/(?P<drw>\d+)/$', 'finaldraw'),
    (r'^addtee/(?P<courseid>\d+)/((?P<id>\d+)/)?$', 'addtee'),
    (r'^adddraw/(?P<tourn>\d+)/$', 'adddraw'),
    (r'^statistics/((?P<trn>\d+)/)?$', 'statistics'),
    (r'^addteeoff/(?P<drw>\d+)/((?P<id>\d+)/)?$', 'addteeoff'),
    (r'^addhole/(?P<teeid>\d+)/((?P<id>\d+)/)?$', 'addhole'),
    (r'^managecourses/$','managecourses'),
    (r'^manageplayers/$','manageplayers'),
    (r'^displaytournaments/$','displaytournaments'),
    (r'^addplayer/((?P<id>\d+)/)?$', 'addplayer'),
    (r'^managehandicaps/$','managehandicaps'),
    (r'^addhandicap/(?P<plr>\d+)/((?P<id>\d+)/)?$', 'addhandicap'),
    (r'^addscores/((?P<matchentry>\d+)/)?$', 'addscores'),
    (r'^addpscores/((?P<prnd>\d+)/)?$', 'addpscores'),
    (r'^managetournaments/$','managetournaments'),
    (r'^managemembers/$','managemembers'),
    (r'^managepracticerounds/$','managepracticerounds'),
    (r'^addtournament/((?P<id>\d+)/)?$', 'addtournament'),
    (r'^addpracticeround/((?P<id>\d+)/)?$', 'addpracticeround'),
    (r'^manageentries/(?P<trn>\d+)/$','manageentries'),
    (r'^managescores/(?P<trn>\d+)/$','managescores'),
    (r'^managetrophies/(?P<trn>\d+)/$','managetrophies'),
    (r'^deletematchentry/(?P<id>\d+)/$','deletematchentry'),
    (r'^addmatchentry/(?P<tourn>\d+)/((?P<id>\d+)/)?$', 'addmatchentry'),
    (r'^addtrophy/(?P<trn>\d+)/((?P<id>\d+)/)?$', 'addtrophy'),
    (r'^showcourse/(?P<id>\d+)/$', 'showcourse'),
    (r'^showresults/(?P<trp>\d+)/$', 'showresults'),
    (r'^showtee/(?P<course>\d+)/(?P<id>\d+)/$', 'showtee'),
    (r'^showscores/(?P<matchentry>\d+)/$', 'showscores'),
    )
